### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by vinaydate** [davidderaedt/CC-Extension-Builder-for-Brackets#18]
I installed the extension as directed.
There was a menu created on 'Main menu' with title 'CC Extension Menu' (Instead of a sub menu as told on http://davidderaedt.github.io/CC-Extension-Builder-for-Brackets).

And in this 'CC Extension Menu', there is a sub menu called 'New Creative Cloud Extension'. It opens up a dialog with title 'Creative Cloud Extension Builder (Beta)'. There are no options for choosing the CC app. And when we chose to create the extension, nothing happens.

Please help.

**Comment by grefel** [comment]
I've the same here with Windows 7 64 bit.  I've got a modified version from https://forums.adobe.com/thread/1564200 working, but in the end you can just copy the boilerplate Plugin into your %appdata% -->  Adobe--> CEP -->Extensions Folder.

**Comment by davidderaedt** [comment]
Chances are you installed from the Brackets extension registry rather from this repo, hence the version you installed was obsolete. I uploaded the latest version (1.0.1) to the registry, so please update your extension from either way, everything should work fine now.

**Comment by grefel** [comment]
I tried both: Install from URL and from the Repository with Release 1.0 Build 1.0.0-15191 (release 3f2eb90a4) Wind7/64bit. The same result, the Menu is added right to "Help" in the main menu and has no function as described above. 

Is there a log which may help to find the problem?

**Comment by davidderaedt** [comment]
First, please make sure you've enabled extension development. Then, choose Debug > Show developer tools, and check any error displaying in the console. There's also a nodelog.txt in the extension's node folder which may help us understand the issue

**Comment by grefel** [comment]
I use Brackets the first time. Where can I enable extension development? 
With Debug -> Show developer Tools i get no errors in the console. 

In nodelog.txt i found:

```
start Wed Nov 12 2014 17:03:47 GMT+0100 (Mitteleuropäische Zeit) -- Platform: win32

Exec:'C:/Users/hp/AppData/Roaming/Brackets/extensions/user/dehats.ccextbuilder/CC-EXT-SDK/createext.bat' default com.example.helloworld'
Error: Command failed: Der Befehl "'C:" ist entweder falsch geschrieben oder
```

konnte nicht gefunden werden.

I'm a little suspicious about: 'Platform: win32' I'm running a 64 bit Windows. The error message is in german a translates to: Cannot execute "'C:"

**Comment by wolfXD** [comment]
You need to update quotation in line 81 of main.js from:
<code>cmd = "'"+sdkFolder.fullPath + "createext.bat" + "' default " + data.extid + '"';</code>
to:
<code>cmd = '"'+sdkFolder.fullPath + "createext.bat" + '" default ' + data.extid;</code>

**Comment by grefel** [comment]
Thanks wolfXD. Now my nodelog.txt contains only 

```
start Wed Nov 12 2014 17:56:45 GMT+0100 (Mitteleuropäische Zeit) -- Platform: win32
```

But this bug would not help with wrong position of the menu entry and the broken dialog window.

**Comment by wolfXD** [comment]
I think that's due to possible upcomming improvements, but that's just a guess...
True, the menu position could be better, but for me it's fair enough ;)
The dialog entries you are missing are commented out in source. Currently you will have to configure your manifest.xml without the help of the dialog.

**Comment by jpatrolla** [comment]
I'm having the same issue. Does this work for mac?

Here's my console log:

```
[brackets-ccext-node] failed to run ccext.execmd Object {killed: false, code: 126, signal: null} main.js:91
(anonymous function) main.js:91
j thirdparty.min.js:559
k.fireWith thirdparty.min.js:559
NodeConnection._receive /utils/NodeConnection.js:494
```

**Comment by wolfXD** [comment]
Just give it a try... ;)
Line 83 of main.js is the mac command.
I can't test it - running Windows only...

You also might want to look into nodelog.txt which should give you more details.

**Comment by jpatrolla** [comment]
Thanks wolf - I was referring to the issue as nothing happening after clicking 'create extension', I get that error in console after I click 'create extension'

**Comment by davidderaedt** [comment]
@grefel @wolfXD Correct - this is the expected position for the menu, and the dialog is meant that way too. You do have to update the manifest manually. I'll check that quote issue on line 81 as soon as I get my hands back on a windows system.

@jpatrolla Yes, it's tested on mac OS. Are you sure you're running Brackets 1.0 and the latest (1.0) version of this extension?

**Comment by jpatrolla** [comment]
Thanks @davidderaedt 
Yeah, I'm on 1.0 and using the latest git extension, running OSX Yosemite.
Prior to this I was using eclipse and the Adobe Extension Builder 3 to play around until I was recommended brackets + your extension.

**Comment by davidderaedt** [comment]
I just published an update restoring the mechanism to force exec permissions on shell scripts of the SDK. Please try reinstalling v 1.0.2 from the URL (as this update is not yet published on the brackets extension registry).

**Comment by jpatrolla** [comment]
Thanks for checking that out @davidderaedt .. Unfortunately I'm still getting errors. Hmmm
Am I right to assume I only need Brackets + This extension and nothing else?

This happens after I 'Create Extension':

```
Error watching project root:  /Users/parca/Library/Application Support/Adobe/CEP/extensions/com.example.helloworld/ Unknown /project/ProjectManager.js:741
(anonymous function) /project/ProjectManager.js:741
```

Cheers,

**Comment by faninx** [comment]
Doesn't work on OS X 10.10.1 & Photoshop CC 2014.2 & Brackets 1.0 & Creative Cloud Extension Builder 1.0.1

Can't enable Debug mode & can't create new extensions.

**Comment by jpatrolla** [comment]
Should have mentioned my programs too. I'm running exactly the same as @faninx

**Comment by davidderaedt** [comment]
The extension was developed and tested against this very same config... minus the extension version. Again, if you guys are running v1.0.1, please migrate to v0.1.2 which fixes permission issues introduced by brackets' extension install process. Ideally, try downloading the zip from this repo and put it on your brackets extension folder manually. And please always check for errors in the console before posting here, as I can't do much about reports stating that it simply "doesn't work".
Thanks for your patience!

**Comment by faninx** [comment]
@davidderaedt Thx, I manually install the extension from github's zip, It's OK now. 
I thought the version in brackets' extension manager was the newest before.

**Comment by Chris2011** [comment]
I use this things and I don't get it working: 

```
Create a self signed certificate for your adobe plugin
    ZXPSignCmd.exe -selfSignedCert DE LE Company Chris abc123 MyCert.p12

Create the zxp file and sign it with the cert.
    ZXPSignCmd.exe -sign C:\Users\****\AppData\Roaming\Adobe\CEP\extensions\com.example.helloworld' ExampleAdobe.zxp MyCert.p12 abc123

Install the plugin via:
    ExManCmd.exe /install C:\Users\*****\Downloads\Adobe\ccextensionswin64\win64\ExampleAdobe.zxp
```

And when I do the last thing, I got this error: failed to install, status = -411. I don't know what I've done wrong. Here is the log file after I called ExManCmd: http://pastebin.com/AQ2sp6Z3

**Comment by vinaydate** [comment]
Moved on to other responsibilities
